### ISSUE TITLE
docker-compose up -d

### ISSUE THREAD

**Issue by zizihaier** [vesoft-inc/nebula-docker-compose#100]
#docker-compose up -d
Creating network "nebula-docker-compose_nebula-net" with the default driver
Creating nebula-docker-compose_metad1_1 ... done
Creating nebula-docker-compose_metad0_1 ... done
Creating nebula-docker-compose_metad2_1 ... done
Creating nebula-docker-compose_storaged0_1 ... done
Creating nebula-docker-compose_storaged2_1 ... done
Creating nebula-docker-compose_storaged1_1 ... done
Creating nebula-docker-compose_graphd_1    ...
Creating nebula-docker-compose_graphd_1    ... error
Creating nebula-docker-compose_graphd1_1   ... done
WARNING: Host is already in use by another container

ERROR: for nebula-docker-compose_graphd_1  Cannot start service graphd: driver failed programming external connectivity Creating nebula-docker-compose_graphd2_1   ... done
rting userland proxy: listen tcp 0.0.0.0:9669: bind: address already in use

ERROR: for graphd  Cannot start service graphd: driver failed programming external connectivity on endpoint nebula-docker-compose_graphd_1 (f5a4f9ee3b7f5f0e8456bad5f55605c0796b5983bef546a0175365924633ba95): Error starting userland proxy: listen tcp 0.0.0.0:9669: bind: address already in use
ERROR: Encountered errors while bringing up the project.

**Comment by wey-gu** [comment]
It's claiming the port is already in use, could you please check on `ss -plunt | grep 9669` to see which process is occupying this port? Or alternatively you could change the `graph` container's ports to avoid this confliction.

**Comment by Sophie-Xie** [comment]
Close it first, and open it if any new info.
