### ISSUE TITLE
docker-compose up -d timeout

### ISSUE THREAD

**Issue by CharleyXu** [vesoft-inc/nebula-docker-compose#103]
➜  nebula-docker-compose git:(v2.0.0) docker-compose up -d

Pulling metad0 (vesoft/nebula-metad:v2.0.0)...
v2.0.0: Pulling from vesoft/nebula-metad
2d473b07cdd5: Pulling fs layer
18b911743d01: Pulling fs layer
7feb5a2056b0: Pulling fs layer
76689905f720: Waiting
ERROR: error pulling image configuration: Get "https://production.cloudflare.docker.com/registry-v2/docker/registry/v2/blobs/sha256/5d/5dead1910498f849db3c2cc859eade6b483f677623bfa72df0f505ff9b63ebea/data?verify=1636012814-Px9dFbCl8tfoXLSoGyVYzOKFTQ4%3D": dial tcp: lookup production.cloudflare.docker.com on 192.168.65.5:53: read udp 192.168.65.4:63494->192.168.65.5:53: i/o timeout

**Comment by wey-gu** [comment]
Is your network in china mainalnd? It could be caused by network instability for docker hub(cloudflare CDN), alternatively you could try with some China docker mirror as your registry.
for example: https://gist.github.com/y0ngb1n/7e8f16af3242c7815e7ca2f0833d3ea6

**Comment by CharleyXu** [comment]
Thanks for your comment，its work ！
