### ISSUE TITLE
Could not open the file: /sys/fs/cgroup/memory/memory.limit_in_bytes

### ISSUE THREAD

**Issue by Jayuda** [vesoft-inc/nebula-docker-compose#111]
helo guys, I try to run nebula with docker-compose version 2.6.0  but show error 

E0213 19:42:59.945086     1 GraphDaemon.cpp:159] Could not open the file: /sys/fs/cgroup/memory/memory.limit_in_bytes

i have clean install still same error.
Thanks

**Comment by wey-gu** [comment]
Dear @Jayuda ,

please go to v2.6 branch(pointing to the latest 2.6.2 image) instead, there are issues on 2.6.0 and 2.6.1 when it comes to CGROUPv2(where in newer docker desktop, its VM is based on CGROUPv2).

https://github.com/vesoft-inc/nebula-docker-compose/tree/v2.6

Thanks.

**Comment by wey-gu** [comment]
BTW, how v2.6.0 was navigated to you, we had already updated docs to point to v2.6 only, did we miss anywhere please?
