### ISSUE TITLE
下载nebula-console版本再连接nebula后，出现 i/o timeout

### ISSUE THREAD

**Issue by jiangpeng12345** [vesoft-inc/nebula-docker-compose#115]
docker run --rm -ti --network nebula-net --entrypoint=/bin/sh vesoft/nebula-console:v2.0.0-rc1

/ # nebula-console -u user -p  passwrod --address=graphd --port=9669
Could not get IPs: lookup graphd on 127.0.0.11:53: read udp 127.0.0.1:33576->127.0.0.11:53: i/o timeout
2022/02/18 12:18:58 Fail to initialize the connection pool, host: graphd, port: 9669, Failed to find IP, error: lookup graphd on 127.0.0.11:53: read udp 127.0.0.1:33576->127.0.0.11:53: i/o timeout
panic: Fail to initialize the connection pool, host: graphd, port: 9669, Failed to find IP, error: lookup graphd on 127.0.0.11:53: read udp 127.0.0.1:33576->127.0.0.11:53: i/o timeout

请问这个问题该如何解决

**Comment by wey-gu** [comment]
请问您的 nebula-graph 的版本是 `v2.0.0-rc1` ？console 需要和 nebula-graph 在对应的版本哈。
可以打印一下 docker ps 看看 compose 的信息么？graphD 是起来的么？

**Comment by Sophie-Xie** [comment]
Close it first, and open it if any new info.

**Comment by fineday009** [comment]
![image](https://github.com/user-attachments/assets/9a72e358-9bac-4c36-9144-c241c2801a98)
![image](https://github.com/user-attachments/assets/ce8948db-00bf-44b8-9879-988d1f78ef3a)

遇到类似的问题，有解决方案吗？
