### ISSUE TITLE
run commond ”docker-compose up -d“ fail

### ISSUE THREAD

**Issue by jiaxian-lin** [vesoft-inc/nebula-docker-compose#117]
Get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

**Comment by wey-gu** [comment]
For China Mainland network, dockerhub may be not stable, you could search from Baidu on "国内 docker hub 镜像", or referring something like: https://gist.github.com/y0ngb1n/7e8f16af3242c7815e7ca2f0833d3ea6
