### ISSUE TITLE
Can we have a light version of docker-compose?

### ISSUE THREAD

**Issue by artemkorsakov** [vesoft-inc/nebula-docker-compose#144]
**General Question**

For integration tests, I would like to have a lightweight version of docker-compose so as not to raise 9 docker images.
Is it possible to somehow get by with only 3 images: `vesoft/nebula-metad`, `vesoft/nebula-storaged`, `vesoft/nebula-graphd`?

For example I would like to write integration tests for https://github.com/vesoft-inc/nebula-spark-connector using https://testcontainers.com/ to check common commands: create space, write vertixes and edges etc.

**Comment by wey-gu** [comment]
Agreed. Are you interested in PR a docker-compose-lite.yaml?

ref: https://gist.github.com/wey-gu/97554f1e84e977a3803c64e6757c452d

**Comment by artemkorsakov** [comment]
Thank you!
Yes, I will definitely create the PR after I test locally that everything works and the tests run :)

**Comment by artemkorsakov** [comment]
Done. Now it remains only to write the correct testcontainer, but I think it will take me several days :(

**Comment by artemkorsakov** [comment]
It successfully runs in `testcontainers` and in integration tests within ci-jobs.
