### ISSUE TITLE
should change the version of console in 3.5.0 docker-compose yaml

### ISSUE THREAD

**Issue by abby-cyber** [vesoft-inc/nebula-docker-compose#147]
https://github.com/vesoft-inc/nebula-docker-compose/blob/3f8a5ee89218bf8ec5afce8090aafa4223fb096f/docker-compose.yaml#L328

Run `git clone -b release-3.5 https://github.com/vesoft-inc/nebula-docker-compose.git` and an error occurred.

![image](https://github.com/vesoft-inc/nebula-docker-compose/assets/78209557/e15413d0-1da4-405f-9b62-8bc4ddc0daf2)

 
The default console version is `nightly` in the 3.5.0 [[docker-compose.yaml](https://github.com/vesoft-inc/nebula-docker-compose/blob/master/docker-compose.yaml)](https://github.com/vesoft-inc/nebula-docker-compose/blob/release-3.5/docker-compose.yaml) . 

Cluster can be normally started after changing the console version to `v3.2.0`

**Comment by Nicole00** [comment]
> https://github.com/vesoft-inc/nebula-docker-compose/blob/3f8a5ee89218bf8ec5afce8090aafa4223fb096f/docker-compose.yaml#L328
> 
> Run `git clone -b release-3.5 https://github.com/vesoft-inc/nebula-docker-compose.git` and an error occurred.
> 
> ![image](https://user-images.githubusercontent.com/78209557/252567940-e15413d0-1da4-405f-9b62-8bc4ddc0daf2.png)
> 
> The default console version is `nightly` in the 3.5.0 [[docker-compose.yaml](https://github.com/vesoft-inc/nebula-docker-compose/blob/master/docker-compose.yaml)](https://github.com/vesoft-inc/nebula-docker-compose/blob/release-3.5/docker-compose.yaml) .
> 
> Cluster can be normally started after changing the console version to `v3.2.0`

thanks for proposing this issue, we'll fix it, and looking forward to your pr too~
