### ISSUE TITLE
`docker run` command throws error

### ISSUE THREAD

**Issue by back-to-eat** [vesoft-inc/nebula-docker-compose#32]
```
docker run --rm -ti --network=host vesoft/nebula-console:nightly --addr=127.0.0.1 --port=3699
E0228 10:57:08.062841     1 GraphClient.cpp:54] Thrift rpc call failed: AsyncSocketException: recv() failed (peer=127.0.0.1:3699, local=127.0.0.1:51044), type = Internal error, errno = 104 (Connection reset by peer): Connection reset by peer
Connection failed
```
This error confused me serveral times. I have to retry till it works. Why is that?
My version:

```
docker run --rm -ti --network=host vesoft/nebula-console:nightly --addr=127.0.0.1 --port=3699

Welcome to Nebula Graph (Version b899838)
```

**Comment by Shylock-Hg** [comment]
The whole service can't be ready immediately, the are a gap time to start the service before you can request the port.

**Comment by yixinglu** [comment]
After you start nebula services by `docker-compose up -d`, you should wait all services of nebula to be ready by checking `docker-compose ps`. If all services are healthy, you can use nebula console to connect nebula graph. 

![image](https://user-images.githubusercontent.com/2520865/79820426-c6c44d80-83be-11ea-8e6c-e919f33d974b.png)
