### ISSUE TITLE
On macos, metad has no leader

### ISSUE THREAD

**Issue by Shinji-IkariG** [vesoft-inc/nebula-docker-compose#34]
When using job manager related commands, I receive an error prompt.
**Environments**
OS: Darwin 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64
Docker version 19.03.8, build afacb8b
docker-compose version 1.25.4, build 8d51620a
CPU:MacBookPro15,4 i7-8557u
Commit id 6499c64

**Steps to reproduce the behavior**:
step1:
Setting up a brand new nebula docker-compose environment

step2:
`docker run --rm -ti --network=host vesoft/nebula-console:nightly --addr=127.0.0.1 --port=3699`

step3:
`CREATE SPACE test;`
`use test;`
`SUBMIT JOB COMPACT;`

(user@127.0.0.1:3699) [test]> SUBMIT JOB COMPACT;
[ERROR (-8)]: Unknown error(409): Leader changed!
Wed Mar 25 18:39:22 2020

**Expected behavior**

`(user@127.0.0.1:3699) [test]> SUBMIT JOB COMPACT;`
`==============`
`| New Job Id |`
`==============`
`| 2          |`
`--------------`
`Got 1 rows (Time spent: 1.64/2.358 ms)`

**Comment by Sophie-Xie** [comment]
Close it first, and open it if any new info.
