### ISSUE TITLE
未设置密码账号，但是还是强制需要

### ISSUE THREAD

**Issue by martixZero** [vesoft-inc/nebula-docker-compose#59]
/usr/local # nebula-console  --address=graphd --port=3699
2020/12/14 07:22:58 Error: username or password is empty!

**Comment by ryanqin01** [comment]
+1

**Comment by yixinglu** [comment]
If you disable the flag: `enable_authorize = false` in `nebula-graph.conf`, you can use any username/password to login nebula service. But it doesn't means you could keep the username/password empty. If you feel it's not what you want, you can give some suggestions in our forums: https://discuss.nebula-graph.com.cn/

**Comment by yixinglu** [comment]
Hi @ryanqin01 and @martixZero if you still have any questions about nebula, you could raise them in our forums: [cn](https://discuss.nebula-graph.com.cn/) & [en](https://discuss.nebula-graph.io/).

Thanks for your feedback, i close the issue now.
