### ISSUE TITLE
update listening ports

### ISSUE THREAD

**Issue by oldLady344** [vesoft-inc/nebula-docker-compose#60]
the default listening ports for storaged, graphd, and metad have been changed. should we update docker-compose.yaml?

**Comment by oldLady344** [comment]
typo?

https://github.com/vesoft-inc/nebula-docker-compose/blob/2a612f1c4f0e2c31515e971b24b355b3be69420a/docker-compose.yaml#L169

**Comment by yixinglu** [comment]
has used the new ports now. Thanks.
