### ISSUE TITLE
Unstable connection and operation failed often

### ISSUE THREAD

**Issue by ianhhhhhhhhe** [vesoft-inc/nebula-docker-compose#63]
Version: v1.nightly
OS: macOS 10.15.7
Docker:20.10.0

I used your composer file to start the service and I use the 'clientExample.py' in the examples. When I run the script, there always some operation will failed. It seems to be very unstable.

**Comment by yixinglu** [comment]
If you use v1.0 branch of this repo, the nebula-python repo branch must be [v1.0](https://github.com/vesoft-inc/nebula-python/tree/v1.0) since there are some compatible issues between v2 and v1 of nebula. So please ensure that the version of nebula client is right.

**Comment by yixinglu** [comment]
I think this issue could be closed now. Thanks for your feedback.
