### ISSUE TITLE
[ERROR (-8)]: Wrong vertex id type: 101

### ISSUE THREAD

**Issue by xupengjun** [vesoft-inc/nebula-docker-compose#76]
根据官方文档操作，无法插入点数据
insert vertex player(name,age) values 101:("Tony Parker", 36);
![image](https://user-images.githubusercontent.com/20333917/109641891-36819800-7b8d-11eb-8b2e-de990f772dda.png)
标签结构是
![image](https://user-images.githubusercontent.com/20333917/109641976-5f099200-7b8d-11eb-81ae-7a51753e22cc.png)
我参考的是官网这个地址
https://docs.nebula-graph.com.cn/manual-CN/1.overview/2.quick-start/1.get-started/
![image](https://user-images.githubusercontent.com/20333917/109642051-78124300-7b8d-11eb-8abf-f2bf3f1db55c.png)

**Comment by Aiee** [comment]
As shown in the first screenshot, you need to choose a space before inserting a vertex.

**Comment by xupengjun** [comment]
![image](https://user-images.githubusercontent.com/20333917/109642555-1900fe00-7b8e-11eb-99ed-e96c115e2617.png)
选择了，还是不对，我的player标签是在schema nba中的，

**Comment by xupengjun** [comment]
> As shown in the first screenshot, you need to choose a space before inserting a vertex.

![image](https://user-images.githubusercontent.com/20333917/109642653-3766f980-7b8e-11eb-9e61-067e42958453.png)
选择了还是不对

**Comment by xupengjun** [comment]
> As shown in the first screenshot, you need to choose a space before inserting a vertex.

我知道怎么回事了，在执行语句时，VID需要用双引号
![image](https://user-images.githubusercontent.com/20333917/109643230-e1df1c80-7b8e-11eb-9f3c-0361d13eedb4.png)

**Comment by Aiee** [comment]
By default, the vertex Id type is ```string```, which causes the problem you see. You can determine the type of vid between ```int``` and ```string``` when creating a new space.

ref: https://docs.nebula-graph.io/2.0/3.ngql-guide/9.space-statements/1.create-space/
