### ISSUE TITLE
ERROR: unknown command line flag 'local_ip'

### ISSUE THREAD

**Issue by codlin** [vesoft-inc/nebula-docker-compose#78]
### Console logs
> CONTAINER ID        IMAGE                                             COMMAND                  CREATED             STATUS                          PORTS                                                                                                  NAMES
> cc0139e1f3e2        vesoft/nebula-graphd:v2-nightly                   "/usr/local/nebula..."   3 minutes ago       Restarting (1) 53 seconds ago                                                                                                          nebula_graphd1_1
> 49f165b1c735        vesoft/nebula-graphd:v2-nightly                   "/usr/local/nebula..."   3 minutes ago       Restarting (1) 50 seconds ago                                                                                                          nebula_graphd_1
> 02a8e5a16155        vesoft/nebula-graphd:v2-nightly                   "/usr/local/nebula..."   3 minutes ago       Restarting (1) 50 seconds ago   
> 
> graphd_1     | ERROR: unknown command line flag 'local_ip'
> graphd_2   | ERROR: unknown command line flag 'local_ip'

no other logs

### Server info
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
              total        used        free      shared  buff/cache   available
Mem:           3828        1240         512          28        2075        2298
Linux VM-0-9-debian 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2 (2017-06-12) x86_64 GNU/Linux

**Comment by lawrencehjf** [comment]
+1 on mac

**Comment by yixinglu** [comment]
Hi @codlin and @lawrencehjf 

Could you check the docker `registry-mirrors` configuration in `/etc/docker/daemon.json` and what's the built time of nebula docker images by the command `docker images`?

AFAIK, some registry mirror providers don't sync the image data in time such that your local images is outdated even if you have pulled them.

**Comment by lawrencehjf** [comment]
as is remember, walkaround by upgrade the nebula image version
